# Generated by Django 3.1.1 on 2020-09-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlisttrackerapp', '0002_auto_20200917_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsong',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
